### ISSUE TITLE
Some question about paper

### ISSUE THREAD

**Issue by henrycjh** [wyysf-98/GenMM#7]
Hi, I have read the paper and take a look at the code, and I hope you could help me figure out the questions below :

1. To get synthesized motions, you first get some nearest patches from example using bidirectional similarity, and then just average the values of all patches since they are overlapping on "time" axis. Why we could get smooth results just using bidirectional similarity?
2. What does "averaging voting" mean in the figure below? I just see averaging values of all patches in your code.
![image](https://github.com/wyysf-98/GenMM/assets/73419275/5cbc01b6-c440-4e30-8396-a94fed8ce4c4)

Thanks for your attention!

**Comment by wyysf-98** [comment]
Hi, thanks for your interest in our work. The two questions have almost the similar question:
1, smooth results are guaranteed by the overlapping patches, which are about 15 frames for each patch. You can imagine that for each generated frame, we average the results of 15 frames from the nearest patches taken from the example. The average makes it smooth;
2, For the first and last {patch // 2} patches, the overlapped frames are less than the patch size, which is like convolution op. So we call it voting rather than a simple average and this word is commonly used in patch-based methods.

**Comment by henrycjh** [comment]
Thanks for your patiently reply!
